name: Dart

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test-dart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dart
        uses: dart-lang/setup-dart@v1.6.2
        with:
          sdk: "3.2.4"

      - name: Testing dart
        run: |
          echo "Install dart dependencies"
          dart pub get
          
          echo "Verify formatting"
          dart format --output=none --set-exit-if-changed .
          
          echo "Analyze project source code"
          dart analyze
