name: Deploy to firebase

on:
  push:
    branches:
      - master

  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build-flutter:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true || github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.7"
          channel: "stable"

      - name: Install flutter dependencies
        run: flutter pub get

      - name: Flutter build for web
        run: flutter build web

      - name: Archive build result
        uses: actions/upload-artifact@v4
        with:
          name: 'flutter web build'
          path: build/web/
          if-no-files-found: error
          overwrite: true

  deploy-firebase:
    runs-on: ubuntu-latest

    needs: build-flutter

    if: github.event.pull_request.merged == true || github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download build result
        uses: actions/download-artifact@v4
        with:
          name: 'flutter web build'
          path: build/web

      - name: Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MODABADA }}'
          channelId: live
          projectId: modabada
