name: Flutter

on:
  pull_request:
    branches:
      - master

jobs:
  test-flutter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"
          channel: "stable"

      - name: Testing flutter
        run: |
          echo "Install flutter dependencies"
          flutter pub get
          
          flutter test
